# Generated by Django 6.0.7 on 2026-07-08 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('accident', 'Accident'), ('nid_de_poule', 'Nid de poule'), ('route_barree', 'Route barrée'), ('vehicule_en_panne', 'Véhicule en panne')], max_length=20)),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('critique', 'Critique')], max_length=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('fusionne', 'Fusionné'), ('resolu', 'Résolu')], default='actif', max_length=10)),
                ('nb_confirmations', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mobility.roadsegment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
